language: ruby
sudo: required

services:
  - docker
script:
  - docker build -t ${DOCKER_HUB_REPO}/${DOCKER_HUB_IMAGE}:${DOCKER_HUB_TAG} .
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin;
      sudo docker push ${DOCKER_HUB_REPO}/${DOCKER_HUB_IMAGE}:${DOCKER_HUB_TAG};
    fi
notifications:
  email:
    recipients:
      - hrishi@portworx.com
      - harsh@portworx.com
    on_success: change
    on_failure: always  